### ISSUE TITLE
Rendering JSON dynamics leads to ScriptRuntimeException

### ISSUE THREAD

**Issue by celaus** [scriban/scriban#334]
Hi, I am confused about something. I am trying to simply render a JSON onto a template - but the object seems to become `Null` somewhere during the rendering/runtime process. 

This snippet fails when parsing and trying to render the template (exception below). As you can see the 
~~~c# 
dynamic jo = JsonConvert.DeserializeObject<ExpandoObject>(@"{ ""Machine"": { ""Name"": ""hello"", ""MachineId"": 123 } }");
Assert.Equal(jo.Machine.Name, "hello");
var content = Template.Parse("<html> <body> <h1>This is a test for Machine {{ Machine.Name }} ({{ Machine.MachineId }})</h1> <span>This is a test for machine {{ Machine.Name }}.</span> </body></html>>").Render(jo);
~~~

When running the snippet above, the following exception occurs. Even after some investigation I can't find why this would be null. In fact if I create the exact same object using the `new {}` syntax, it works flawlessly...
~~~
Error Message:
   Scriban.Syntax.ScriptRuntimeException : <input>(1,57) : error : Cannot get the member Machine.Name for a null object.
  Stack Trace:
     at Scriban.Syntax.ScriptMemberExpression.GetValue(TemplateContext context)
   at Scriban.TemplateContext.GetOrSetValue(ScriptExpression targetExpression, Object valueToSet, Boolean setter)
   at Scriban.TemplateContext.GetValue(ScriptExpression target)
   at Scriban.Syntax.ScriptMemberExpression.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Syntax.ScriptExpressionStatement.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Syntax.ScriptBlockStatement.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Syntax.ScriptPage.Evaluate(TemplateContext context)
   at Scriban.TemplateContext.Evaluate(ScriptNode scriptNode, Boolean aliasReturnedFunction)
   at Scriban.Template.EvaluateAndRender(TemplateContext context, Boolean render)
   at Scriban.Template.Render(TemplateContext context)
   at Scriban.Template.Render(Object model, MemberRenamerDelegate memberRenamer, MemberFilterDelegate memberFilter)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
[...]
~~~

.NET core 3.1; scriban versions 3.0.5 and 3.5.0 lead to the same result.

/cc @mtirionMSFT

**Comment by celaus** [comment]
If the name wouldn't be found, the rendered output would be just the text (e.g. because of the member naming being upper case), but it looks like we don't even get that far.

**Comment by celaus** [comment]
Ah ok, although it does work if I create the same object using a literal `new { Machine = new { Name = .. } }`. It works now indeed, thanks!
